### ISSUE TITLE
Instruction should be added

### ISSUE THREAD

**Issue by ypwalter** [vivekn/sentiment-web#1]
For ways to start up redis server or people should install python-devel before pip install

**Comment by vivekn** [comment]
It worked fine for me without python-devel on OSX and Ubuntu. Though setuptools is a dependency of pip.

**Comment by ypwalter** [comment]
I was using Ubuntu 12.04 and it doesn't work smooth until I found that installation of python devel is required. Also, some instructions on redis server (perhaps 1~2 lines of instruction would be good)

**Comment by ypwalter** [comment]
btw, it was me who was using the api continuous for days. sorry about that it was annoying (and I finally set up my own server) and thank you.

**Comment by vivekn** [comment]
Added the instruction for redis, btw thanks for using the API
