### ISSUE TITLE
Question: Could you explain the contents of the reducedata.pickle file?

### ISSUE THREAD

**Issue by jonatho7** [vivekn/sentiment-web#5]
Hi,

Could you explain the contents of the reducedata.pickle file?

Does this file store the values for pos, neg, and totals?

As a short example, what does the following info in the file convey?:

sS'not_a very bad'
p7
I50
sS'not_lonely'
p8
I60
sS'simply not'
p9
I11

sS = phrase contents
p7 = phrase 7
I50 = ???

And is reducedata.pickle used when feature selection is turned off, or is this file only used with feature selection?

Any help here would be great!

**Comment by vivekn** [comment]
Its just a serialized dump of a couple of hash tables containing counts data of different terms, so that the pretrained data can be used for the API. It is the result obtained after applying feature selection to the original training set.

https://docs.python.org/2/library/pickle.html
